export const SkillsToolsList = {
  "fe-web": [
    { path: "/icons-language/html5.svg", name: "HTML5" },
    { path: "/icons-language/css.svg", name: "CSS3" },
    { path: "/icons-language/javascript.svg", name: "JavaScript" },
    { path: "/icons-library/react.svg", name: "React.js" },
    { path: "/icons-framework/tailwindcss.svg", name: "Tailwind CSS" },
    { path: "/icons-framework/vite.svg", name: "Vite" },
    { path: "/icons-library/axios.svg", name: "Axios" },
  ],
  "fe-app": [
    { path: "/icons-library/react.svg", name: "React" },
    { path: "/icons-framework/capacitor.svg", name: "Capacitor" },
    { path: "/icons-design/pwa.svg", name: "PWA" },
    { path: "/icons-design/responsive.svg", name: "Responsive Design" },
  ],
  be: [
    { path: "/icons-library/nodejs.svg", name: "Node.js" },
    { path: "/icons-framework/expressjs.svg", name: "Express.js" },
    { path: "/icons-design/rest-api.svg", name: "REST APIs" },
    { path: "/icons-library/jwt.svg", name: "JWT" },
    { path: "/icons-library/passportjs.svg", name: "Passport.js" },
    { path: "/icons-library/socketio.svg", name: "Socket.io" },
    { path: "/icons-software/rabbitmq.svg", name: "RabbitMQ" },
    { path: "/icons-design/microservices.svg", name: "Microservices" },
  ],
  db: [
    { path: "/icons-database/mongodb.svg", name: "MongoDB" },
    { path: "/icons-database/mysql.svg", name: "MySQL" },
    { path: "/icons-library/mongoose.svg", name: "Mongoose" },
    { path: "/icons-database/sequelize.svg", name: "Sequelize" },
  ],
  ai: [
    { path: "/icons-ai/llm.svg", name: "LLM Integration" },
    { path: "/icons-ai/prompt-engineering.svg", name: "Prompt Engineering" },
    { path: "/icons-ai/ai-extraction.svg", name: "AI Data Extraction" },
    { path: "/icons-ai/ai-workflows.svg", name: "AI Workflows" },
  ],
  tools: [
    { path: "/icons-software/git.svg", name: "Git" },
    { path: "/icons-software/github.svg", name: "GitHub" },
    { path: "/icons-software/postman.svg", name: "Postman" },
    { path: "/icons-software/vscode.svg", name: "VS Code" },
    { path: "/icons-software/npm.svg", name: "npm" },
    { path: "/icons-hosting/vercel.svg", name: "Vercel" },
    { path: "/icons-software/railway.svg", name: "Railway" },
    { path: "/icons-software/aws.svg", name: "AWS" },
    { path: "/icons-software/redis.svg", name: "Redis" },
  ],
  others: [
    { path: "/icons-language/javascript.svg", name: "JavaScript" },
    { path: "/icons-language/cpp.svg", name: "C++" },
    { path: "/icons-language/c.svg", name: "C" },
  ],
};
